#pact:
 # verifier:
  #  publishResults: true
#pactbroker:
 # url: http://localhost:9292
spring:
  application:
    name: curso-arquitectura
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://${MYSQL_URL}:3306/${MYSQL_DB}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true