name: Continuos Deployment
on:
  push:
    branches:
      - main
jobs:
  build:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        name: Descargando el repo
      - name: Instalar Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: gradle/gradle-build-action@v3
        name: Instalando lo mejor - gradle
      - name: Compilando ando
        run: ./gradlew build
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: danielsabana/curso
          tags: ${{ github.sha }}
          registry: docker.io
          dockerfile: Dockerfile
          username: danielsabana
          password: Daniel.28


